services:
  # Servidor web Apache amb PHP i suport MySQL
  web:
    image: ebota/daw:apache_php_mysql_mongodb
    container_name: incidencia-web
    ports:
      - "8080:80"
    volumes:
      - ./projecte:/var/www/html
    command: /bin/bash -c "composer install --no-interaction --no-plugins --no-scripts; apache2-foreground"
    depends_on:
      - db
    networks:
      - app-network

  # Servidor de base de dades MySQL
  db:
    image: mysql:8.0
    container_name: gestorIncidencia-db
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: gestorIncidencia
      MYSQL_USER: usuari
      MYSQL_PASSWORD: usuari1234
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # Adminer per gestionar la base de dades
  adminer:
    image: adminer
    container_name: gestorIncidencia-adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: gestorIncidencia-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user1234
      MONGO_INITDB_DATABASE: gestor-incidencias
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mysql-data:
  mongo-data:

networks:
  app-network:
    driver: bridge